import { ProjectItem } from './types';

export const PROJECTS_DATA: ProjectItem[] = [
  {
    id: 'osmins-landscaping',
    title: "Osmin's Landscaping",
    category: 'Premium Family Greenscaping',
    accentColor: '#10b981',
    badge: '01. LANDSCAPING ATELIER',
    tech: ['Metro Atlanta Serv', 'Sod Installation', 'Retaining Walls', 'Irrigation Sys'],
    description: 'Over 20 years of family-operated landscaping expertise servicing a 60-mile radius around Marietta and Metro Atlanta with live dynamic sod selections.',
    linkText: 'Launch Landscaping Portal',
    linkUrl: 'https://osmins-landscaping.netlify.app/',
    glow: 'rgba(16, 185, 129, 0.12)',
  },
  {
    id: 'bela-vista',
    title: 'Bela Vista Nature Resort',
    category: 'Elite Minimal Nature Cove',
    accentColor: '#d97706',
    badge: '02. RESORT LANDING',
    tech: ['Saint Martin Cove', 'Rustic Cottages', 'Sunset Vlog Logs', 'Open-Fire Dining'],
    description: 'A minimalist slow-living nature cove on Saint Martin island overlooking the Bay of Bengal, featuring rustic beach cottages and open-fire culinary menus.',
    linkText: 'Browse Sunset Cove',
    linkUrl: 'https://bela-vista-pied.vercel.app/',
    glow: 'rgba(217, 119, 6, 0.12)',
  },
  {
    id: 'rene-architect',
    title: 'Rene Architect Studio',
    category: 'Biophilic Geo Architecture',
    accentColor: '#84cc16',
    badge: '03. RAW MODERN DESIGN',
    tech: ['Kazi Fahim Nasir', 'Chittagong Studio', 'Eco Geometries', '3-Stage Framework'],
    description: 'Chittagong-based architectural practice honoring biophilic harmony, sustainable workspaces, and clean organic concrete geometries.',
    linkText: 'Inspect Architectural Plans',
    linkUrl: 'https://rene-architect.netlify.app/',
    glow: 'rgba(132, 204, 22, 0.12)',
  },
  {
    id: 'ceramic-enthusiasts',
    title: 'Ceramic Enthusiasts',
    category: 'Premium Detailing Studio',
    accentColor: '#3b82f6',
    badge: '04. AUTOMOTIVE PROTECTION',
    tech: ['Houston Outpost', 'Liquid PPF Shield', '10H Nano Ceramic', 'One-Car-At-Time'],
    description: 'Veteran-owned automotive detailing studio based in Houston Metro with a strict one-car-at-a-time focus on liquid premium paint-protection film & ceramics.',
    linkText: 'Protect Your Vehicle',
    linkUrl: 'https://ceramic-enthusiasts.netlify.app/',
    glow: 'rgba(59, 130, 246, 0.12)',
  },
  {
    id: 'clean-home',
    title: 'Family Services Cleaning',
    category: 'Pet-Safe Hygiene Systems',
    accentColor: '#06b6d4',
    badge: '05. ECO HOME BIOPHILICS',
    tech: ['Zero Toxic Chemicals', 'HEPA Sanitization', 'Allergen Reduction', 'Garage Restoring'],
    description: 'Family-centered residential hygiene systems utilizing 100% biodegradable botanical non-toxic formulas built for allergen-free pet safe wellness.',
    linkText: 'Schedule Guard Shine',
    linkUrl: 'https://clean-home-power-washing.netlify.app/',
    glow: 'rgba(6, 182, 212, 0.12)',
  },
  {
    id: 'pencil-link',
    title: 'Pencil Link Outsourcing',
    category: 'AI Auto & SaaS Growth Unit',
    accentColor: '#a855f7',
    badge: '06. SaaS ENGINE & GROWTH',
    tech: ['Custom SaaS Build', 'AI Agent Workflows', 'Outbound Sales Gen', 'Brand Identity'],
    description: 'A cohesive bundled team providing complete custom software development, automated AI agent workflows, and outbound high-growth lead engines.',
    linkText: 'Outsource Growth Squad',
    linkUrl: 'https://pencillink.tech/',
    glow: 'rgba(168, 85, 247, 0.12)',
  }
];
